# Stubs for invoke.runners (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Optional, Tuple, Dict, List

# We are stubbing other peoples stuff, ignore errors related to that code.
# pylint: disable = missing-class-docstring, too-many-public-methods,
# pylint: disable = too-few-public-methods, unused-argument, missing-docstring
# pylint: disable = invalid-name, too-many-arguments, no-self-use


class Result:
    stdout: str = ...
    stderr: str = ...
    encoding: str = ...
    command: str = ...
    shell: str = ...
    env: Dict[str, str] = ...
    exited: int = ...
    pty: bool = ...
    hide: Tuple[str] = ...

    def __init__(
            self,
            stdout: str = "",
            stderr: str = "",
            encoding: Optional[str] = ...,
            command: str = "",
            shell: str = "",
            env: Optional[Dict[str, str]] = ...,
            exited: int = 0,
            pty: bool = False,
            hide: Tuple[str] = (),
    ) -> None:
        ...

    @property
    def return_code(self) -> int:
        ...

    def __nonzero__(self) -> bool:
        ...

    def __bool__(self) -> bool:
        ...

    @property
    def ok(self) -> bool:
        ...

    @property
    def failed(self) -> bool:
        ...

    def tail(self, stream: str, count: int = ...) -> List[str]:
        ...
