# Stubs for exifread (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import io
from typing import Dict

from exifread.classes import IfdTag


def process_file(
        f: io.BytesIO,
        stop_tag: str = ...,
        details: bool = ...,
        strict: bool = ...,
        debug: bool = ...,
) -> Dict[str, IfdTag]:
    ...
