# Stubs for exifread.classes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Union, List


class IfdTag:
    printable: str
    tag: int
    field_type: int
    field_offset: int
    field_length: int
    values: Union[str, List[Union[int, str]]]

    def __init__(
            self,
            printable: str,
            tag: int,
            field_type: int,
            values: Union[str, List[Union[int, str]]],
            field_offset: int,
            field_length: int,
    ) -> None:
        ...


#  class ExifHeader:
#      file: Any = ...
#      endian: Any = ...
#      offset: Any = ...
#      fake_exif: Any = ...
#      strict: Any = ...
#      debug: Any = ...
#      detailed: Any = ...
#      tags: Any = ...

#      def __init__(
#              self,
#              file: Any,
#              endian: Any,
#              offset: Any,
#              fake_exif: Any,
#              strict: Any,
#              debug: bool = ...,
#              detailed: bool = ...
#      ) -> None:
#          ...

#      def s2n(self, offset: Any, length: Any, signed: int = ...):
#          ...

#      def n2s(self, offset: Any, length: Any):
#          ...

#      def list_ifd(self):
#          ...

#      def dump_ifd(
#              self,
#              ifd: Any,
#              ifd_name: Any,
#              tag_dict: Any = ...,
#              relative: int = ...,
#              stop_tag: Any = ...
#      ) -> None:
#          ...

#      def extract_tiff_thumbnail(self, thumb_ifd: Any) -> None:
#          ...

#      def extract_jpeg_thumbnail(self) -> None:
#          ...

#      def decode_maker_note(self) -> None:
#          ...

#      def parse_xmp(self, xmp_string: Any) -> None:
#          ...
